### ISSUE TITLE
couldn't get level TypeError

### ISSUE THREAD

**Issue by istmmi** [WebDollar/Node-WebDollar#169]
This keeps coming up while solo mining WebDollar on Linux Ubuntu 18, in terminal.

couldn't get level TypeError: Cannot read property 'difficultyTarget' of undefined
After this exception, the hashrate goes down to 0 hashes/s.

Also: BAAAAAANNNNS and BAAAAAAAAAAAN keeps coming up.

**Comment by ibudisteanu** [comment]
Did you encounter the issue on the new master versions? I believe the issue was fixed in the meanwhile. Also did have the entire blockchain? We introduced a parameter that completely sync is not possible and you need to download the blockchain and you are able to download only the last 50k blocks from the full nodes.

The BANS can happen for multiple reasons. If you encounter the issues again, let me know and reopen the issue.
