### ISSUE TITLE
Time it took to mine last 10 blocks is incorectly calculated

### ISSUE THREAD

**Issue by cristiwn** [WebDollar/Node-WebDollar#9]
Issue is is function static getDifficultyMean( getDifficultyCallback, getTimeStampCallback, blockTimestamp, blockNumber)

The formula for calculating total time it took to mine last 10 blocks doesn't consider the timestamp of (firstblock -1)
. e.g, for calculating time it took to mine first block it would need to subtract timestamp of previous block from the timestamp of first block.
 Even more , adding all the timestamps(firstblock to blocknumber(or firstblock+9)) and than subtrating 10x timestamp of firstblock is not a correct formula for getting the time it took to mine all the blocks.
![img_20180329_102314](https://user-images.githubusercontent.com/35920125/38084063-28edc6ac-3354-11e8-864c-92d00570e405.jpg)

A more direct formula would only include timestamps of previous block before firstblock and blocknumber(last block generated before hitting next%10==0). It is enough to just subtract these 2 timestamps in order to get the time that passed in between.
![img_20180329_102641](https://user-images.githubusercontent.com/35920125/38084080-32785da4-3354-11e8-8e0f-3c8f6fff6193.jpg)

**Comment by ibudisteanu** [comment]
Hi Cristi!

We really appreciate the time invested in analyzing the Block Creation Time and for reporting the issue in this formal way. Also, some users have reported the issue that the average generation block time is ~ 40-45 seconds instead of 20 seconds (TIME_PER_BLOCK). The current implementation was written from scratch and we could deploy it very soon in the next update.

I think you are right. After a step by step debug, I saw that the function getForkTimeStamp(height) that I used, returns the timestamp of the height-1 instead of height. So, the line

```
            for (let i = firstBlock; i < blockNumber; i++) {
                console.warn("getTimeStampCallback",  getTimeStampCallback(i));
                how_much_it_took_to_mine_X_Blocks += getTimeStampCallback(i);
            }
```
indeed it will return the timestamps of blocks [-1,0, .. ,7]

then it adds the timestamp of block [9]  // current block

```
            how_much_it_took_to_mine_X_Blocks += blockTimestamp;
```
so the timestamp is based on the blocks [-1,0...7] U [9] instead of the blocks [0...9]

Moreover, also when I calculate the timestamp how_much_it_took_to_mine_X_Blocks, I use again the timestamp of block -1

```
how_much_it_took_to_mine_X_Blocks -= (consts.BLOCKCHAIN.DIFFICULTY.NO_BLOCKS) * getTimeStampCallback(firstBlock);
```

how_much_it_took_to_mine_X_Blocks = 10 * block[-1].timestamp

where instead of block[-1] should have been block[0]

Besides this code bug in getDifficulty function detailed by me above based on your issue report, are there any more bugs?

This report is valid and you will be rewarded with Bug Bounty

I will make a Fix Today, and I will post the Commit Link :smile: 

In case you didn't use, you can use Chrome Debugger to simulate and debug the code in Browser. So, debugging and simulating will help you faster to analyze all the parameters. Here is a tutorial regarding the tool in chrome in case you didn't use it already. https://youtu.be/KbEx0s06VLs?t=3m9s

**Comment by ibudisteanu** [comment]
What I don't understand is how you got the conclusion that the software calculates the following formula

![image](https://user-images.githubusercontent.com/17750489/38086533-62a9cbc6-335d-11e8-8af1-98c4ac9f0c76.png)

**Comment by ibudisteanu** [comment]
let's suppose consts.BLOCKCHAIN.DIFFICULTY.NO_BLOCKS is 10 (as it is today).

Is the formula `10*11/2`*block[0].timestamp or `9*10/2`*block[0].timestamp

**Comment by ibudisteanu** [comment]
Commit to Fix these 2 issues in the Formula https://github.com/WebDollar/Node-WebDollar/commit/528d19b24adec9c581a420d1962f1b6a4219639b

**Comment by ibudisteanu** [comment]
Report #1 was also included in the timestamp validation. A did a commit to fix that issue https://github.com/WebDollar/Node-WebDollar/commit/9251613c9293f9ef2e3506909f5894834acc51e8
